version: '3'
services:
    database:
        build: database
        container_name: mysql
        hostname: mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - singlepage-network
        ports:
            - "3306:3306"
        volumes:
            - ./data-volume:/var/lib/mysql

    backend:
        build: backend
        container_name: flask
        hostname: flask
        networks:
            - singlepage-network
        ports:
            - "5000:5000"
        volumes:
            - $PWD/config.yaml:/usr/src/app/config/config.yaml
        restart: always
        depends_on:
            - database
networks:
  singlepage-network:
    driver: bridge